services:
  gordianbla:
    build:
      context: .
      args:
        - MONGODB_URI=mongodb://mongo:27017/gordianbla
    environment:
      NODE_ENV: production
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - gordianbla_db:/data/db

volumes:
  gordianbla_db:
